### ISSUE TITLE
EEPROM Error

### ISSUE THREAD

**Issue by dslee525** [lwfinger/rtl8188eu#396]
Dear,

I have a problem with RTL8188EUS. I would appreciate it if you share your idea.

Our board isn't PC, it's imx6ul(NXP AP) and ARM. Kernel 5.4.14(Yocto dunfell)

When rtl8188eus(USB type) is attached, I can find it using lsusb.
**- Messages -**
Bus 001 Device 002: ID 0bda:8179 Realtek Semiconductor Corp. RTL8188EUS 802.11n Wireless Network Adapter
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

And here is the other messages in dmesg when I insert a kernel module(8188eu.ko). Of course, the firmware(rtl8188eufw.bin) was placed into /lib/firmware/rtlwifi on a target board.
**- Messages -**
[  219.705478] usb 1-1: new high-speed USB device number 2 using ci_hdrc
[  219.907482] usb 1-1: New USB device found, idVendor=0bda, idProduct=8179, bcdDevice= 0.00
[  219.907530] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  219.907563] usb 1-1: Product: 802.11n NIC
[  219.907593] usb 1-1: Manufacturer: Realtek
[  219.907623] usb 1-1: SerialNumber: 00E04C0001
[  390.555103] 8188eu: loading out-of-tree module taints kernel.
[  390.612559] Chip Version Info: CHIP_8188E_Normal_Chip_TSMC_D_CUT_1T1R_RomVer(0)
[  391.655424] EEPROM ID(0xff00) is invalid!!
[  391.655452] EEPROM ID = 0xff00
[  391.681979] usbcore: registered new interface driver r8188eu

But it's not working well. And I can have an error as I use ifconfig.
**- Messages -**
root@imx6ul-var-dart:~# ifconfig wlan1 up
SIOCSIFFLAGS: Operation not permitted

I lost the way to debug it. It's really helpful if you give me any ideas.   :)

Best regards,

**Comment by lwfinger** [comment]
Your card is broken. The EEPROM contains a number of parameters needed for the chip to operate correctly; however, something has happened to yours. If these parameters were the only thing in the EEPROM, then we could provide a shadow version from RAM, but the on-board CPU in the rtl8188eus bootstraps from the EEPROM.

The error in the iwconfig call is likely due to your kernel not being generated with CONFIG_WEXT enabled.

As these chips are quite cheap ($10 or less) at Ebay.com, I suggest you replace it. It would not be worth the effort to work around the faulty EEPROM. Besides, we have no idea what other problems the chip might have.

**Comment by dslee525** [comment]
Thank you for your advice,
I will try to get new one as soon as possible. :)

**Comment by dslee525** [comment]
New one arrived~ And I test it, but it's not working well.

First, you are correct. I can get a EEPROM ID.
- log -
[  505.745385] usb 1-1: new high-speed USB device number 2 using ci_hdrc
[  505.947310] usb 1-1: New USB device found, idVendor=0bda, idProduct=8179, bcdDevice= 0.00
[  505.947363] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  505.947394] usb 1-1: Product: 802.11n NIC
[  505.947426] usb 1-1: Manufacturer: Realtek
[  505.947457] usb 1-1: SerialNumber: 00E04C0001
[  516.144746] 8188eu: disagrees about version of symbol module_layout
[  702.457901] 8188eu: loading out-of-tree module taints kernel.
[  702.504018] Chip Version Info: CHIP_8188E_Normal_Chip_TSMC_D_CUT_1T1R_RomVer(0)
[  702.536953] EEPROM ID = 0x8129
[  702.561354] usbcore: registered new interface driver r8188eu

Second, it's not working well when I use iw scan command. Of course I enabled related WEXT options in kernel. (I think this kernel hasn't excactly same options)
- log -
root@imx6ul-var-dart:~# iw dev wlan1 scan
command failed: No such device (-19)

- kernel options -
CONFIG_WIRELESS=y
CONFIG_WIRELESS_EXT=y
CONFIG_WEXT_CORE=y
CONFIG_WEXT_PROC=y
CONFIG_WEXT_SPY=y
CONFIG_WEXT_PRIV=y
CONFIG_CFG80211_WEXT=y


Third, I'm a little strange because this module(8188eu.ko) doesn't use mac80211 or cfg80211.
- log -
root@imx6ul-var-dart:~# lsmod
Module                  Size  Used by
8188eu                790528  0
mac80211              425984  0
brcmfmac              237568  0
brcmutil               16384  1 brcmfmac
cfg80211              335872  2 mac80211,brcmfmac
imx_sdma               28672  2

I would highly appreciate it if you share your opinion. :)

**Comment by lwfinger** [comment]
It will not use mac80211, but it should use cfg80211. The problem was that the Makefile was not turning it on.

Pull and make again.

I am a little concerned about that "8188eu: disagrees about version of symbol module_layout" warning. That implies that the kernel headers or the gcc version differ between the kernel and this driver. On X86_64, the kernel refuses to load the module. It seems to have been loaded, but I am not sure it will work.

**Comment by dslee525** [comment]
Thank you for your advice, This issue was solved. I use wpa_supplicant, and there are many problems with kernel configuration. RFKILL, CFG80211. And driver is perfect for this kernel version!

**Comment by dslee525** [comment]
I highly appreciate your help and advices. :)
