### ISSUE TITLE
Is it normal to have to recompile the driver every time the kernel is updated? 

### ISSUE THREAD

**Issue by Mart994** [lwfinger/rtl8188eu#398]
I am currently using Fedora 35, kernel 5.16, I use this driver for my tplink TL-WN722N v2
The thing is that since I bought the adapter, every time there is a kernel update (practically once a week) I have to do 'make all' and 'sudo make install' again no matter if it is a minor update like for example 5.16.0 to 5.16.1 or 5.16.1-111 to 5.16.1-123 (I don't remember the exact numbers, I hope you get the idea)
Is that how it works? Am I doing something wrong?

**Comment by lwfinger** [comment]
A long time ago (~20 years or so), Linux was more forgiving than it is now, but the developers found that they were wasting a lot of time chasing bugs that ultimately turned out to be caused by building an external driver against modified kernel headers. To prevent this condition, Linux changed to require that every module be built using EXACTLY the same kernel headers, which describe memory layout of critical structures, AND the same version of gcc as that may affect optimization of those layouts. The short answer is yes, you must rebuild the drivers whenever the kernel changes.

If you want to automate the process, checkout implementing DKMS, which will automatically build the drivers whenever the kernel changes. For the kernel modules of VirtualBox, the service in Linux that starts the VB drivers has a script that builds them if they do not exist. It is not DKMS, but accomplishes the same result.
