### ISSUE TITLE
Bug in rtw_proc.c at v5.2.2.4

### ISSUE THREAD

**Issue by nalla** [lwfinger/rtl8188eu#431]
When compiling with kernel version > 3.10.0 and < 5.17.0 the code in rtw_proc.c is buggy. `PDE_DATA` is only defined when version is below `3.10.0`: https://github.com/lwfinger/rtl8188eu/blob/v5.2.2.4/rtw_proc.c#L28

But it is used when kernel version is below `5.17.0`: https://github.com/lwfinger/rtl8188eu/blob/v5.2.2.4/rtw_proc.c#L207

So for versions ranging from >3.10.0 till <5.17.0 this code errors out.

**Comment by lwfinger** [comment]
Your statement is not correct.

I did the following on my mainline source:
git checkout 5.15
grep -r PDE_DATA include/

The response below shows that PDE_DATA is clearly in kernel 5.15.
include/linux/proc_fs.h:extern void *PDE_DATA(const struct inode *);
include/linux/proc_fs.h:static inline void *PDE_DATA(const struct inode *inode) {BUG(); return NULL;}

Further testing shows that it is in a VANILLA kernel from 3.10 to 5.17, inclusive.

What I suspect is that your distro has backported some change so that their source looks like 5.18, or later. As this change is specific to your distro, it is impossible for me to support. How many varieties should I support? I chose to support only the mainline kernel, thus my code is designed to build this source. If your distro has changed the availability of certain features, then you will need to revise your copy. If I were to meet your requirements, I would break the driver for everyone but people using your distro. As that would include me, I am not going to do it.
